[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  
  # Belirli bir fonksiyonun zaman aşımı süresini artır
  [functions."handle-call"]
    timeout = 25 # Saniye cinsinden
